# Generated by Django 4.1.4 on 2022-12-28 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(null=True)),
                ('name_project', models.TextField(null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('who', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/avatars/')),
                ('role', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('tools', models.TextField(null=True)),
                ('interest', models.TextField(null=True)),
                ('work_time', models.TextField(null=True)),
                ('GMT', models.TextField(null=True)),
                ('date_reg', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(max_length=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
